### ISSUE TITLE
shared_clock_node.h in examples/imx6sx_nit6sx_m4 wrong?

### ISSUE THREAD

**Issue by mau-tux** [boundarydevices/freertos-boundary#1]
Hi,
in examples/imx6sx_nit6sx_m4 wrong/shared_clock_node.h is reported a list of clocks that is the same for imx6sx_sdb board. But in imx6sx-nitrogen6sx-m4.dts from linux-imx6 tree (boundary-imx_4.1.15_2.0.0_ga branch) fewer clocks are listed.
Shouldn't these two list be equal?

Regards
Mauro

**Comment by gibsson** [comment]
Hi Mauro,

Like the comment says in shared_clock_node.h: "Here we assume every clock node is shared".

But in the device tree we actually only declare the clocks that could actually be useful for the M4, especially to run the examples.

Declaring all the clocks as shared in Linux isn't great because it means it will never turn off any of them in case they are used.

Then, if your application requires another clock to be shared, you'll have to add it to the device tree but keep in mind that the setup, as available today, is only here as an example. Each application is different and might require different clock settings.

Regards,
Gary

**Comment by gibsson** [comment]
Hi Mauro,

Actually you are right, the list has to match exactly between those two files. Good catch!

I reopen this bug for now, I'll update the dts to have all the clocks, this way it will better for other people (in case they want to use ECSPI2 for instance which isn't declared right now).

I'll let you know once the dts is updated.

Regards,
Gary

**Comment by gibsson** [comment]
Hi Mauro,

I've pushed the change to both 4.1.15 branches. Let me know if you have any question.

Thanks again for reporting this.

Regards,
Gary

**Comment by mau-tux** [comment]
Hi Gary,
Yes, it seems all right now.

Thank you for having fixed it so quickly.

Regards,
Mauro
